### ISSUE TITLE
「愛知コロナ情報」という名称について

### ISSUE THREAD

**Issue by kotobuki** [code4aichi/corona#1]
基本的には素晴らしい取り組みだと思っております。「愛知コロナ情報」という略称ベースの名称はわかりやすさを優先されたのだと思いますが、風評被害等を考慮すると変更すべきではないかと考えます。例えばですが、「愛知県内における新型コロナウイルス感染症に関する情報」「愛知県内新型コロナウイルス感染情報」のようにするのはいかがでしょうか。ご検討のほど、どうぞよろしくお願いいたします。

**Comment by Miura55** [comment]
@kotobuki issueありがとうございます。Code for AICHIの運営メンバーです。名称の件承知しました。ぜひ、前向きに検討させていただきます。

**Comment by code4aichi** [comment]
ご指摘ありがとうございました。レスポンシブを考慮して、サイト名を「愛知新型コロナウイルス感染情報」に修正いたしました。
